### PR TITLE
Transfer the Chrome extension into an Edge one

### PR DESCRIPTION
**Pull request by EE-LiuYunhao**
## Testing: 
The extension can be added to MS Edge as long as long as the "Enable the developers to load extension" flag is turned on in the [about:flags](url). 
It seems that the MS Edge does not store the data to google chrome server; however, the courseHTML array is stored and loaded sucessfully every time. 

## Existing Bugs / Future developments for EDGE version
1. **Enable the sync.**
    As mentioned above, since the EDGE does not sync with google servers, the sync across devices is currently disabled.
1. **Auto loading** 
   It might be possible to use a spider programme _(personally speaking, PowerShell may be suitable for this job ^\_^)_ to retrieve the enrollment data for each semester from hkuportal. Thus, there is no need for users to make selection on their own. 
1. **Color & length for each HTML element in `innercontainer`**
    It seems that the hku moodle has upgrade their style a bit _(maybe it is the randering issue of the EdgeHTML...)_. Consequentely, the buttons for adding / removal of courses have difference in color and size with the others. However it is not a big issue at all. Y(^\_^)Y

### CODE REVIEW

**Comment by AENeuro** [comment]
_It is beyond my wildest imagination that someone would actually open a PR on this. So thank you for the support. It might not sound like it but it really means a lot to me._ 🎉🎉🎉Thanks Dave.

Porting is always a good thing b/c we're offering convenience to more users. Although in this case I personally don't think a PR is the best idea. This repo is for Chrome and Chrome only (and I don't see how we can support two platforms in one repo, without bringing thousand lines of extra code onto the existing platform). 

Nonetheless the idea of bridging the API is insanely awesome and may be helpful to many!! And you are more than welcomed to fork a "HKU-Moodle-Helper-Edge" as you like.

Stay in touch bro.

**Comment by AENeuro** [comment]
### Re: Existing Bugs / Future developments

* **Enable the sync:**
Keep me updated! If Chrome allows for that in the future it would be crazy!
* **Auto loading:**
If we're talking about chrome then the extension can access, analyse and store the HKU Portal page content directly (**all without the CORS fuss!**). 
Although the necessity of such a move is uncertain. Adding such a function wouldn't really bring too much convenience (for me personally, b/c it literally takes me less than one minute to add all the courses). 
And how exactly do you know which course moodle is corresponding to which course (e-learning page provides a link, but not a "name" of the module). So it has to be a collab between multiple pages then.

* **Color & length for each HTML element in** `innercontainer` **:**
Yes that is something to work on. I am using a built-in button CSS class for now. Maybe next time should work on UI a little bit.

Thanks!!

**Comment by EE-LiuYunhao** [comment]
Hi~

As for sync, the MS is said to merge Chromium core into their Edge browser. I suppose perhaps the MS Edge may support the sync better afterwards. 

I am really new to front-end developing and am not quite familiar with the button formatting in browser extensions. I may need to spend more time in figuring out how to make those buttons look alike. 

BTW, if you believe that separating the two versions as different repos is better, may I then close the pull request?

**Comment by AENeuro** [comment]
I personally doubt if picking up a Chromium Core would give MS access to Google servers tho. 

Buttons: I made the buttons look different cuz they have different functions. It could be styled better still.

Yes can close the PR. Thanks again.

**Pull request closed without merging**
